kind: Deployment
apiVersion: apps/v1
metadata:
# set your user name
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  volumes:
    - name: index-html
      configMap:
        name: index.html
        defaultMode: 420
  selector:
    matchLabels:
# set your user name
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
# set your user name
        app: {{ .Release.Name }}
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: {{ .Release.Name }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: index-html
              mountPath: /tmp/html # this will mount the html.index file to it application location
# update with the iamge you build in part 1
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10