kind: Deployment
apiVersion: apps/v1
metadata:
# set your user name
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
# set your user name
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
# set your user name
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: index-html
          configMap:
            name: index.html
            defaultMode: 420
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /health/readiness # this check the application url path
              port: {{ .Values.containers.containerPort  }} # In which port the Application is listening
              scheme: HTTP
            initialDelaySeconds: 1 # the time is waiting befor testing the application path
            timeoutSeconds: 1 # the time for timeout
            periodSeconds: 10 # the abount of time to wait between checks
            successThreshold: 1 # count to decalre seccessfull 
            failureThreshold: 3 # count to decalre failure
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: {{ .Values.containers.containerPort }}
              scheme: HTTP
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: PORT
              value: {{ .Values.containers.containerPort | quote }}  
          terminationMessagePath: /dev/termination-log
          name: {{ .Release.Name }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: index-html
              mountPath: /tmp/html
# update with the iamge you build in part 1
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10